import Navigation from "../components/navigation"
import "../styles/global.css"
import styles from "../styles/Main.module.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <div className={styles.container}>
          {children}
        </div>
      </body>
    </html>
  )
}
